ALTER TYPE "ConversationStatus" ADD VALUE IF NOT EXISTS 'NEW';
ALTER TYPE "ConversationStatus" ADD VALUE IF NOT EXISTS 'CONTACTED';
ALTER TYPE "ConversationStatus" ADD VALUE IF NOT EXISTS 'PROPOSAL';
