export type AuditLogAction =
  | "CREATE"
  | "UPDATE"
  | "DELETE"
  | "USER_LOGIN"
  | "USER_LOGOUT"
  | "WORKSPACE_CREATED"
  | "WORKSPACE_UPDATED"
  | "ROLE_ASSIGNED"
  | "ROLE_REVOKED"
  | "IMPERSONATION_STARTED";
